[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:stack]
command=/bin/bash /app/start.sh
directory=/app
autostart=true
autorestart=true

stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stdout_logfile_backups=0

stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stderr_logfile_backups=0
